export default {
  Places: [
    {
      city: "Paulo",
      country: "Brazil",
      id: 1,
      title: "Cozy Apartment",
      description:
        "A comfortable and stylish apartment in the heart of the city 1.",
      location: "Downtown, Austria",
      price_per_night: 150,
      number_of_bedrooms: 2,
      number_of_bathrooms: 2,
      max_guests: 4,
      amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
      image: ["/a1.webp", "/a2.webp", "/a3.webp", "/a4.webp", "/a5.webp"],
      host: "Camelia",
      career: "Trainer",
      stars: "4.2",
      reviews: "4",
      cost: "150",
      img: "/a1.webp",
    },
    {
      city: "Toronto",
      country: "Canada",
      id: 2,
      title: "Seaside Villa",
      description:
        "A luxurious villa with breathtaking ocean views and direct beach access 2.",
      location: "Beachfront, Coastal Town 2",
      price_per_night: 350,
      number_of_bedrooms: 4,
      number_of_bathrooms: 3,
      max_guests: 8,
      amenities: [
        "Ocean View",
        "Private Beach",
        "Swimming Pool",
        "Hot Tub",
        "BBQ Grill",
      ],
      image: ["/img1.png", "/img2.png", "/img3.png", "/img4.png", "/img5.png"],
      host: "Robert",
      career: "Trainer 2",
      stars: "4.9",
      reviews: "4",
      cost: "250",
      img: "/img1.png",
    },
    {
      city: "Torino",
      country: "Italy",
      id: 3,
      title: "Rustic Cabin",
      description:
        "Escape to a peaceful cabin surrounded by nature and wildlife 3.",
      location: "Forest Retreat, Wilderness 3",
      price_per_night: 80,
      number_of_bedrooms: 1,
      number_of_bathrooms: 1,
      max_guests: 2,
      amenities: [
        "Nature Trails",
        "Fireplace",
        "Pet-Friendly",
        "Outdoor Seating",
        "No Wi-Fi",
      ],
      image: ["/b1.webp", "/b2.webp", "/b3.webp", "/b4.webp", "/b5.webp"],
      host: "Kelvin",
      career: "Host 3",
      stars: "4.56",
      reviews: "4",
      cost: "331",
      img: "/img1.png",
    },
    {
      city: "Lyon",
      country: "France",
      id: 4,
      title: "Cute Apartment ",
      description:
        "A comfortable and stylish apartment in the heart of the city 4.",
      location: "Downtown, Cityname ",
      price_per_night: 150,
      number_of_bedrooms: 2,
      number_of_bathrooms: 1.5,
      max_guests: 4,
      amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
      image: ["/b1.webp", "/b2.webp", "/b3.webp", "/b4.webp", "/b5.webp"],
      host: "Albert",
      career: "Entrepreneur 4",
      stars: "3.56",
      reviews: "4",
      cost: "442",
      img: "/img1.png",
    },
    {
      city: "Milan",
      country: "Italy",
      id: 5,
      title: "Seaside Castle ",
      description:
        "A luxurious villa with breathtaking ocean views and direct beach access 5.",
      location: "Beachfront, Coastal Town 5",
      price_per_night: 350,
      number_of_bedrooms: 4,
      number_of_bathrooms: 3,
      max_guests: 8,
      amenities: [
        "Ocean View",
        "Private Beach",
        "Swimming Pool",
        "Hot Tub",
        "BBQ Grill",
      ],
      image: ["/img1.png", "/img2.png", "/img3.png", "/img4.png", "/img5.png"],
      host: "Rock",
      career: "Coach Trainer 5",
      stars: "3.5",
      reviews: "4",
      cost: "634",
      img: "/img1.png",
    },
    {
      city: "Lindfield",
      country: "UK",
      id: 6,
      title: "Rustic Cabin ",
      description:
        "Escape to a peaceful cabin surrounded by nature and wildlife 6.",
      location: "Forest Retreat, Wilderness 6",
      price_per_night: 80,
      number_of_bedrooms: 1,
      number_of_bathrooms: 1,
      max_guests: 2,
      amenities: [
        "Nature Trails",
        "Fireplace",
        "Pet-Friendly",
        "Outdoor Seating",
        "No Wi-Fi",
      ],
      image: ["/a1.webp", "/a2.webp", "/a3.webp", "/a4.webp", "/a5.webp"],
      host: "Kris",
      career: "Food Artist 6",
      stars: "4.56",
      reviews: "4",
      cost: "234",
      img: "/img1.png",
    },
  ],
};
