export const Places = [
  {
    city: "Paulo",
    country: "Brazil",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/luxury.jpg",
    host: "Camelia,",
    career: "Trainer",
  },
  {
    city: "Toronto",
    country: "Canada",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/villa.jpg",
    host: "Robert",
  },
  {
    city: "Torino",
    country: "Italy",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kelvin",
    career: "Host",
  },
  {
    city: "Lyon",
    country: "France",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 1.5,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/cabin.jpg",
    host: "Albert",
    career: "Entreprenuer",
  },
  {
    city: "Milan",
    country: "Italy",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/castle.jpg",
    host: "Rock",
    career: "Coach trainer",
  },
  {
    city: "Lindfield",
    country: "UK",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kris",
    career: "Food Artist",
  },
  {
    city: "Paulo",
    country: "Brazil",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/luxury.jpg",
    host: "Camelia,",
    career: "Trainer",
  },
  {
    city: "Toronto",
    country: "Canada",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/villa.jpg",
    host: "Robert",
  },
  {
    city: "Torino",
    country: "Italy",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kelvin",
    career: "Host",
  },
  {
    city: "Lyon",
    country: "France",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 1.5,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/cabin.jpg",
    host: "Albert",
    career: "Entreprenuer",
  },
  {
    city: "Milan",
    country: "Italy",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/castle.jpg",
    host: "Rock",
    career: "Coach trainer",
  },
  {
    city: "Lindfield",
    country: "UK",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kris",
    career: "Food Artist",
  },
  {
    city: "Paulo",
    country: "Brazil",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 2,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/luxury.jpg",
    host: "Camelia,",
    career: "Trainer",
  },
  {
    city: "Toronto",
    country: "Canada",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/villa.jpg",
    host: "Robert",
  },
  {
    city: "Torino",
    country: "Italy",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kelvin",
    career: "Host",
  },
  {
    city: "Lyon",
    country: "France",
    id: 1,
    title: "Cozy Apartment",
    description:
      "A comfortable and stylish apartment in the heart of the city.",
    location: "Downtown, Cityname",
    price_per_night: 150,
    number_of_bedrooms: 2,
    number_of_bathrooms: 1.5,
    max_guests: 4,
    amenities: ["Wi-Fi", "Kitchen", "TV", "Washer/Dryer", "Free Parking"],
    image: "/cabin.jpg",
    host: "Albert",
    career: "Entreprenuer",
  },
  {
    city: "Milan",
    country: "Italy",
    id: 2,
    title: "Seaside Villa",
    description:
      "A luxurious villa with breathtaking ocean views and direct beach access.",
    location: "Beachfront, Coastal Town",
    price_per_night: 350,
    number_of_bedrooms: 4,
    number_of_bathrooms: 3,
    max_guests: 8,
    amenities: [
      "Ocean View",
      "Private Beach",
      "Swimming Pool",
      "Hot Tub",
      "BBQ Grill",
    ],
    image: "/castle.jpg",
    host: "Rock",
    career: "Coach trainer",
  },
  {
    city: "Lindfield",
    country: "UK",
    id: 3,
    title: "Rustic Cabin",
    description:
      "Escape to a peaceful cabin surrounded by nature and wildlife.",
    location: "Forest Retreat, Wilderness",
    price_per_night: 80,
    number_of_bedrooms: 1,
    number_of_bathrooms: 1,
    max_guests: 2,
    amenities: [
      "Nature Trails",
      "Fireplace",
      "Pet-Friendly",
      "Outdoor Seating",
      "No Wi-Fi",
    ],
    image: "/cabin.jpg",
    host: "Kris",
    career: "Food Artist",
  },
];
